package com.snezana.introtelecom.exceptions;

public enum RestAPIErrorMessage {

    ITEM_NOT_FOUND,
    WRONG_ITEM,
    ITEM_IS_NOT_UNIQUE,
    ITEMS_NOT_MATCH,
    INVALID_DATE_TIME_FORMAT,
    INVALID_STARTDATETIME_OR_ENDDATETIME,
    INVALID_INPUT_FORMAT,
    VALUE_CANNOT_BE_NEGATIVE,
    PARAMETER_CANNOT_BE_NULL;

}

